name: Send Email on Models Folder Change

on:
  push:
    branches:
      - main  # Change if you're using another branch
    paths:
      - 'models/**'  # Trigger only if files in models/ change

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install nodemailer
        run: npm install nodemailer

      - name: Get Latest Commit Message
        id: get_commit
        run: |
          echo "commit_message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "Commit Message: $commit_message"

      - name: Send Email
        run: node sendMail.js "${{ env.commit_message }}"
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
