name: Send Email on Models Folder Change

on:
  push:
    branches:
      - main
    paths:
      - 'models/**'

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install nodemailer
        run: npm install nodemailer

      - name: Get Changed Files in Models Folder
        id: files
        run: |
          # Get list of changed files in models/ folder
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- models/)
          echo "changed_files<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          # Get list of newly added files in models/ folder
          NEW_FILES=$(git diff --name-only --diff-filter=A ${{ github.event.before }} ${{ github.sha }} -- models/)
          echo "new_files<<EOF" >> $GITHUB_ENV
          echo "$NEW_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Email
        run: |
          node sendMail.js "${{ env.changed_files }}" "${{ env.new_files }}"
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
